baseURL = "https://jmousqueton.github.io/"
languageCode = "en"
title = "Resume Julien Mousqueton"
theme = "resume"

[params.matomo]
        enable = true
        siteId = 1
        url = "stats.mousqueton.io"
        enableJs = true
        enableImg = false
        [[params.matomo.list]]
        option = "disableCookies"
        [[params.matomo.list]]
        option = "trackPageView"
        [[params.matomo.list]]
        option = "enableLinkTracking"


[params]
    author = "Julien Mousqueton"
    description = "Resume - Julien Mousqueton - Chief Technology Officer"
    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Julien Mousqueton"
        tagline = "Chief Technology Officer"
        avatar = "avatar.png"

    [params.available]
      enable  = true

      [params.drivinglicence]
      enable = false

    [params.contact]
        enable = true
        location = "Nogent sur Marne, France"
        BirthDate = "1976-07-01"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:+33633556428"
        text = "06 33 55 64 28"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:julien@mousqueton.me"
        text = "julien@mousqueton.me"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://www.julienmousqueton.fr"
        text = "www.julienmousqueton.fr"

	[params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Cloud Architecture"
        [[params.skills.list.items]]
        details = "Virtualization"
        [[params.skills.list.items]]
        details = "Storage"
        [[params.skills.list.items]]
        details = "Network"
        [[params.skills.list.items]]
        details = "Security"
        [[params.skills.list.items]]
        details = "Automation"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team Leader"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Management"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BSc in Computer Science"
        university = "[Teesside University](https://www.tees.ac.uk/), Middlesbrough, UK"
        dates = "1998 - 1999"
		[[params.education.list]]
        degree = "DUT Informatique"
        university = "[Technology Institut Leonard de Vinci](https://www.iut-rcc.fr/), Reims, France"
        dates = "1996 - 1998"
        [[params.education.list]]
        degree = "Bachelor's degree in Mathematics"
        university = "[Lycée Clemenceau](http://www.lycee-clemenceau-reims.fr/), Reims"
        dates = "1996"

    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "VMware vExpert"
        body = "[NSX & Cloud](https://vexpert.vmware.com/directory/218)"
        date = "2007-2020"
        [[params.awards.list]]
        name = "Cisco Champion"
        body = "Datacenter"
        date = "2010-2020"
   	  	[[params.awards.list]]
        name = "Veeam Vanguard"
        body = "[Vanguard](https://www.veeam.com/vanguard.html)"
        date = "2019-2020"
	 	[[params.awards.list]]
        name = "Nutanix Champion"
        body = ""
        date = "2019"
 	   [[params.awards.list]]
        name = "HPE Ambassador"
        body = ""
        date = "2017-2021"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "French"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Business Fluent, C1"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Rugby"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"

    [params.summary]
        enable = true
        text = "As a Chief Technology Officer at Computacenter, I’m responsible for the strategy, sales enablement and technical proposition development for Hybrid IT. I'm running an integrated strategy and engagement with our customers and partners across our service portfolio."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Chief Technologist Hybrid IT"
        dates = "2018 - Present"
        company = "[Computacenter](https://www.computacenter.com)"
        details = "As Chief Technologist for Hybrid IT, I'm a member of the Datacenter & Cloud Leadership team and I'm driven to ensure Computacenter France continued growth and relevance in the market via offering compelling propositions and services to the market. I'm specifically responsible for the development and maintenance of our strategy ownership of our proposition stack within the Hybrid IT portfolio. I lead a team of Solution Leaders and collectively we are helping to drive our reputation in the market and assist our customers in very complex Digital Transformation programmes. I'm the recognised thought leader for Computacenter in the topic of Hybrid Cloud and as such a large amount of time is dedicated to working with our customer community and market analysts in evangelising Computacenter's capabilities, our approaches and perspectives on the topic. I'm heavily involved in a number of key customer campaigns, both in establishing strategy but also specifically in driving the scope and direction for transformational change to support and underpin the business imperatives."
        [[params.experience.list.items]]
        details = "Definition of Technology offers."
        [[params.experience.list.items]]
        details = "Technology Watch."
        [[params.experience.list.items]]
        details = "Technical Enablement."
        [[params.experience.list.items]]
        details = "Strategy and Design of Responses."
        [[params.experience.list.items]]
        details = "Evangelisation."

        [[params.experience.list]]
        title = "Practice Leader Datacenter & Cloud"
        dates = "2016 - 2018"
        company = "[Computacenter](https://www.computacenter.com)"
        details = "I work within the Datacenter & Cloud business in France and I'm responsible for technical strategy and direction, new proposition development and Sales enablement. I directly support our Solutions Sales team and our internal technical teams to develop compelling service offerings to support our clients strategic objectives and differentiate Computacenter in the marketplace."
        [[params.experience.list.items]]
        details = "Develop the strategy for the Datacenter and Cloud Line of Business."
        [[params.experience.list.items]]
        details = "Speaker for various IT events."
        [[params.experience.list.items]]
        details ="Partners Relationship."
        [[params.experience.list.items]]
        details ="Technical & sales enablement."

        [[params.experience.list]]
        title = "Solution Architect"
        dates = "2015 - 2016"
        company = "[Computacenter](https://www.computacenter.com)"
        details = "As a Datacenter Solution Owner, I'm leading Datacenter focussed technology transformation. I'm responsible for all aspects of Computacenter's technical solution, including technical delivery, quality and alignment to defined requirements. I lead the technical team of ~15 consultants delivering a complex cross technology programme including centered on VMware portfolio."
        [[params.experience.list.items]]
        details = "Technical lead on VMware Solution."
        [[params.experience.list.items]]
        details = "Technical lead on Cloud transformation project."
        [[params.experience.list.items]]
        details = "Pre-Sales Technical Consultant."
        [[params.experience.list.items]]
        details = "Technical enablement."

        [[params.experience.list]]
        title = "Head of Architects and Engineers"
        dates = "2012 - 2015"
        company = "[Groupe AGRICA](https://www.groupagrica.com)"
        details = "I'm in charged of both Architects and Engineers teams. Architects Team is in charge of all new projects (technical and business) and the Engineers team is in charge of the deployement and the MRO."
        [[params.experience.list.items]]
        details = "Assessment of systems architecture currently in place and work with technical staff to recommend the improvment solutions."
        [[params.experience.list.items]]
        details = "Team management (2 Architects & 10 Engineers)"
        [[params.experience.list.items]]
        details = "Continuous research of current and emerging technologies and advice of changes where needed."
        [[params.experience.list.items]]
        details = "Technical counterpart for the CISO."

        [[params.experience.list]]
        title = "Solution Architect"
        dates = "2007 - 2012"
        company = "[Groupe AGRICA](https://www.groupagrica.com)"
        details = "I design and modify systems architecture to meet business requirements. I'm also in charge of the transformation of IT from a legacy model into an 'As a Service' model."
	     [[params.experience.list.items]]
        details = "Define and build the technical infrastructure : LAN, SAN and virtualization."
        [[params.experience.list.items]]
        details = "Implement ITIL process : change and configuration."
        [[params.experience.list.items]]
        details = "Design and deploy a CDP architecture on two Datacenter."

        [[params.experience.list]]
        title = "Datacenter Architect"
        dates = "2002 - 2007"
        company = "Natexis Altaïr"
        details = "I'm responsible for the design of hosting services for our custoners and assessment of business impacts."
	    [[params.experience.list.items]]
        details = "Answering RFP."
        [[params.experience.list.items]]
        details = "Design Solution."
        [[params.experience.list.items]]
        details = "Security."
        [[params.experience.list.items]]
        details = "Training."

        [[params.experience.list]]
        title = "Security Architect"
        dates = "2001 - 2002"
        company = "Caisse Primaire d'Assurance Maladie"
        details = "I coordinate the strategy and operations for the protection of the enterprise information assets and manage that program."
        [[params.experience.list.items]]
        details = "Deploy Internet access and URL Filtering."
        [[params.experience.list.items]]
        details = "Evolve the Backup strategy."
        [[params.experience.list.items]]
        details = "Maintain the security level of the company."


    [params.information]
        enable = true

        [[params.information.list]]
           title = "Professional Certifications"
           [[params.information.list.items]]
              details = "2020 · Sales, Presales, Veeam"
           [[params.information.list.items]]
              details = "2020 · Sales, Presales, AWS"
           [[params.information.list.items]]
              details = "2019 · Sales, Presales, VMware"
           [[params.information.list.items]]
              details = "2018 · NPSX, Nutanix"
           [[params.information.list.items]]
              details = "2018 · ACE, Turbonomic"

		    [[params.information.list]]
           title = "Community"
               [[params.information.list.items]]
		       details = "[Veeam User Group](http://community.veeam.com) France former co-leader."
		       [[params.information.list.items]]
		       details = "VMUG France former leader."
		       [[params.information.list.items]]
		       details = "Active [blogger](https://www.julienmousqueton.fr)."


    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/JMousqueton"
        title = "JMousqueton"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/julien.mousqueton"
        title = "Julien Mousqueton"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/JMousqueton"
        title = "@JMousqueton"

        [params.speaker]
            enable = true

            [[params.speaker.list]]
            details = "2020 · [Podcast](http://www.podcast-usp.fr/) Stockage"
            [[params.speaker.list]]
            details = "2019 · IDC, Paris"
            [[params.speaker.list]]
            details = "2018 · Gartner Symposium, Barelona"
            [[params.speaker.list]]
            details = "2017 · Microsoft Ignite, Paris"
            [[params.speaker.list]]
            details = "2010 · Cisco Live, Barcelona"
            [[params.speaker.list]]
            details = "2008 · VMworld, Las Vegas"
